#!/usr/bin/env python
import sys
from urllib2 import urlopen
try:
  from bs4 import BeautifulSoup as BS4
except ImportError:
  exit('Missing dependency: BeautifulSoup4')

usage = 'Usage: ./bolor <query>'

if __name__ == "__main__":
  try:
    q = sys.argv[1]
  except IndexError:
    exit(usage)

  bolor_url = "http://bolor-toli.com/index.php?pageId=10"
  data = "direction=mn-en&search={}&go=%C2%A0Go%C2%A0"

  http_resp = urlopen(bolor_url, data.format(q))
  resp_text = http_resp.read()

  soup = BS4(resp_text)
  for tr in soup.find(id='wtbl1').find_all('tr')[1:11]:
    if tr.find('a'):
      print tr.find('a').text

# TODO: take X words out of each word classes
# e.g. 5 nouns, 5 verbs
