#!/usr/bin/env python
import sys
import argparse
from urllib2 import urlopen

try:
    from bs4 import BeautifulSoup as BS4
except ImportError:
    exit("Missing dependency: BeautifulSoup4")

parser = argparse.ArgumentParser(
    description='Look up words from Bolor dictionary.',
    prog='bolor')
parser.add_argument('word')


def display(line):
    " Colorful output to stdout "
    line += "(Reset)\n"

    line = line.replace("(Gray)", "\033[0;90m")
    line = line.replace("(Reset)", "\033[0m")

    sys.stdout.write(line)
    sys.stdout.flush()


if __name__ == "__main__":
    args = parser.parse_args()

    bolor_url = "http://www.bolor-toli.com/dictionary/word?"
    data = "selected_lang=4-1&search={}"

    soup = BS4(urlopen(bolor_url, data.format(args.word)).read())
    word_types = [
        "noun",
        "verb",
        "adjective",
        "adverb",
        "other",
    ]
    result = {}
    rows = soup.select("#exact_translations table tr")
    if not rows:
        exit("Not Found")

    for row in rows:
        # Skip non-result rows
        if not row.select(".link-string"):
            continue

        word_type = row.select("td")[3].select("span")[1].text or "[other]"
        word_type = word_type.split("]")[0][1:]  # "[noun][comp.]" -> "noun"
        word = row.select(".link-string")[0].text

        result.setdefault(word_type, []).append(word)

    # Display
    for word_type in word_types:
        if len(result.get(word_type, [])) > 0:
            display("(Gray)%s" % word_type)

        for word in result.get(word_type, []):
            display("  %s" % word)
