#!/usr/bin/env python3
import argparse
import textwrap
from itertools import groupby
from urllib.request import urlopen
from urllib.parse import urlencode, quote

try:
    from bs4 import BeautifulSoup as BS4
except ImportError:
    exit("Missing dependency: BeautifulSoup4")

    
parser = argparse.ArgumentParser(
    description='Look up words from Bolor dictionary.',
    prog='bolor')
parser.add_argument('query', help='search word')

bolor_url = "http://www.bolor-toli.com/dictionary/word?"
parameters = {
    'selected_lang': '4-1',
    'see_usages': 'false',
    'see_variants': 'false'
}

def display_result(result):
    if not result:
        exit('Not Found')

    it_result = groupby(result, lambda x: x['category'])

    for category, category_result in it_result:
        print(category)
        for word in category_result:
            print(textwrap.indent(word['text'], '  '))

            
def bolor_query(word):

    parameters['search'] = quote(word)
    url = ''.join([bolor_url, urlencode(parameters)])
    response = urlopen(url)

    soup = BS4(response.read(), "html.parser")

    result = []
    rows = soup.select("#exact_translations table tr")

    for row in rows:
        if not row.select(".link-string"):
            continue

        category = row.select("td")[3].select("span")[1].text
        word = row.select(".link-string")[0].text

        result.append({
            'category': category or "[uncategorized]",
            'text': word
        })
    result = sorted(result, key=lambda x: x['category'])
    return result


if __name__ == "__main__":
    args = parser.parse_args()

    if not args.query:
        parser.print_help()
        exit()

    result = bolor_query(args.query)
    display_result(result)
