#!/bin/bash
# from: https://faq.i3wm.org/question/83/how-to-run-i3lock-after-computer-inactivity/

scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
rm /tmp/screenshot.png
i3lock -i /tmp/screenshotblur.png
