#!/bin/bash
# from: https://faq.i3wm.org/question/83/how-to-run-i3lock-after-computer-inactivity/

scrot /tmp/screenshot.png
convert /tmp/screenshot.png -scale 5% -scale 2000% /tmp/screenshot.png
i3lock -u -i /tmp/screenshot.png
